#!/usr/bin/env bash
# ==================================================
#  KoolDots (2026)
#  Project URL: https://github.com/LinuxBeginnings
#  License: GNU GPLv3
#  SPDX-License-Identifier: GPL-3.0-or-later
# ==================================================
# Thin wrapper: the rofi hack picker (thumbnails, descriptions, Alt+P live
# preview, Alt+C hacks.conf editing) lives in the packaged
# swaylock-screensaver-select (swaylock-plugin-screensaver RPM/deb; canonical
# source is swaylock-plugin's contrib/screensaver). This wrapper pins this
# config's rofi theme, state file, thumbnail cache, and terminal.
#
# Bound to SUPER SHIFT L. Preview windows float via the "from the XScreenSaver"
# title rule in configs/WindowRules.conf.

if ! command -v swaylock-screensaver-select >/dev/null; then
  notify-send -i "${XDG_CONFIG_HOME:-$HOME/.config}/swaync/images/error.png" \
    "Screensaver picker" \
    "swaylock-plugin-screensaver is not installed -- no hack picker on this host."
  exit 1
fi

export HACK_STATE="${HACK_STATE:-${XDG_CONFIG_HOME:-$HOME/.config}/hypr/.swaylock_hack}"
export SCREENHACK_SHOT_DIR="${SCREENHACK_SHOT_DIR:-${XDG_CACHE_HOME:-$HOME/.cache}/screenhack-shots}"
export SCREENHACK_ROFI_THEME="${SCREENHACK_ROFI_THEME:-${XDG_CONFIG_HOME:-$HOME/.config}/rofi/config-screenhack.rasi}"
export SCREENHACK_TERMINAL="${SCREENHACK_TERMINAL:-kitty}"

# ---------------------------------------------------------------------------
# Fit the picker to the screen it opens on.
#
# The shipped theme asks for 9 rows of 88px thumbnails, which needs roughly
# 850px of height before chrome -- taller than the whole panel on a small
# device (the uConsole is 1280x720 logical), so the list gets clipped top and
# bottom. The packaged picker passes the theme to rofi as `-config` and
# forwards nothing else, so the only lever is the theme file itself: generate
# a small overlay that imports the shipped theme and overrides the geometry.
#
# Overridable: SCREENHACK_ROWS, SCREENHACK_ICON_SIZE, SCREENHACK_WIDTH_PCT.
# Set SCREENHACK_NO_AUTOFIT=1 to use the shipped theme unchanged.
# ---------------------------------------------------------------------------
autofit_theme() {
    [ "${SCREENHACK_NO_AUTOFIT:-0}" = "1" ] && return 0
    [ -r "$SCREENHACK_ROFI_THEME" ] || return 0
    command -v hyprctl >/dev/null 2>&1 || return 0

    # Logical height of the focused output. Rotated outputs (transform 1/3/5/7)
    # swap width and height; scale divides both.
    local geom
    geom=$(hyprctl monitors -j 2>/dev/null | python3 -c '
import json,sys
try: mons = json.load(sys.stdin)
except Exception: sys.exit(1)
m = next((x for x in mons if x.get("focused")), mons[0] if mons else None)
if not m: sys.exit(1)
w, h, sc, tr = m["width"], m["height"], m.get("scale", 1) or 1, m.get("transform", 0)
if tr in (1, 3, 5, 7): w, h = h, w
print(int(w/sc), int(h/sc))
' 2>/dev/null) || return 0
    [ -n "$geom" ] || return 0

    local lw lh
    lw=${geom%% *}; lh=${geom##* }
    [ "$lh" -gt 0 ] 2>/dev/null || return 0

    # Icon size scaled to the panel; smaller screens get smaller thumbnails so
    # more than a couple of rows still fit.
    local icon
    if   [ "$lh" -lt  600 ]; then icon=48
    elif [ "$lh" -lt  800 ]; then icon=56
    elif [ "$lh" -lt 1100 ]; then icon=72
    else                          icon=88
    fi
    icon="${SCREENHACK_ICON_SIZE:-$icon}"

    # Reserve room for the input bar, the message line, window padding and a
    # margin, then fit whole rows into what is left. Floor of 3 rows.
    local spacing=6 reserved=170 rows
    rows=$(( (lh - reserved) / (icon + spacing) ))
    [ "$rows" -lt 3 ] && rows=3
    rows="${SCREENHACK_ROWS:-$rows}"

    # Narrow panels want more of the width than the shipped 55%.
    local width
    if [ "$lw" -lt 1400 ]; then width=90; else width=55; fi
    width="${SCREENHACK_WIDTH_PCT:-$width}"

    local dir="${XDG_CACHE_HOME:-$HOME/.cache}/screenhack"
    mkdir -p "$dir" 2>/dev/null || return 0
    local fitted="$dir/theme-autofit.rasi"
    cat >"$fitted" <<RASI || return 0
/* Generated by ScreenHackSelect.sh -- do not edit.
   Fitted to a ${lw}x${lh} logical screen. */
@import "$SCREENHACK_ROFI_THEME"

listview { lines: $rows; }
element-icon { size: ${icon}px; }
window { width: ${width}%; }
RASI
    export SCREENHACK_ROFI_THEME="$fitted"
}

autofit_theme

exec swaylock-screensaver-select "$@"
