# ==================================================
#  hyprland-wm-config (fork of LinuxBeginnings/Hyprland-Dots)
#  Project URL: https://github.com/syndr/hyprland-wm-config
#  Upstream:    https://github.com/LinuxBeginnings/Hyprland-Dots
#  License: GNU GPLv3
#  SPDX-License-Identifier: GPL-3.0-or-later
# ==================================================
# Commands and Apps to be executed at launch

exec-once = hyprpm reload
exec-once = dex --autostart
#exec-once = blueman-applet
#exec-once = ags
exec-once = $scriptsDir/KeybindsLayoutInit.sh
exec-once = hyprctl setcursor Broodwar 24
exec-once = /usr/bin/kwalletd6
exec-once = copyq --start-server
exec-once = pw-play ~/Music/notifications/Error\ Spam.ogg
