#!/usr/bin/env bash

set -u

WAYBAR_DIR="${HOME}/.config/waybar"
CONFIG_DIR="${WAYBAR_DIR}/configs"
WIDE_TEMPLATE="${CONFIG_DIR}/[TOP] Greenscreen"
NARROW_TEMPLATE="${CONFIG_DIR}/[TOP] Greenscreen Narrow"
UBER_NARROW_TEMPLATE="${CONFIG_DIR}/[TOP] Greenscreen Uber-Narrow"
OUTPUT_FILE="${CONFIG_DIR}/[TOP] Greenscreen Auto"
WIDTH_THRESHOLD="${WAYBAR_NARROW_THRESHOLD:-1500}"
UBER_NARROW_THRESHOLD="${WAYBAR_UBER_NARROW_THRESHOLD:-900}"

is_rotated_transform() {
  case "$1" in
    1|3|5|7) return 0 ;;
    *) return 1 ;;
  esac
}

detect_hypr_socket() {
  local preferred="${XDG_RUNTIME_DIR}/hypr/${HYPRLAND_INSTANCE_SIGNATURE:-}/.socket.sock"

  if [ -S "$preferred" ]; then
    printf '%s\n' "$preferred"
    return 0
  fi

  find "${XDG_RUNTIME_DIR}/hypr" -maxdepth 2 -type s -name '.socket.sock' -printf '%T@ %p\n' 2>/dev/null \
    | sort -nr \
    | head -n1 \
    | cut -d' ' -f2-
}

get_hypr_monitors_json() {
  local monitors_json=""
  local socket_path=""

  if command -v hyprctl >/dev/null 2>&1; then
    monitors_json="$(hyprctl monitors -j 2>/dev/null)" || monitors_json=""
    if [ -n "$monitors_json" ] && [ "$monitors_json" != "[]" ]; then
      printf '%s\n' "$monitors_json"
      return 0
    fi
  fi

  if command -v socat >/dev/null 2>&1; then
    socket_path="$(detect_hypr_socket)"
    if [ -n "$socket_path" ] && [ -S "$socket_path" ]; then
      monitors_json="$(printf 'j/monitors' | socat - UNIX-CONNECT:"$socket_path" 2>/dev/null)" || monitors_json=""
      if [ -n "$monitors_json" ] && [ "$monitors_json" != "[]" ]; then
        printf '%s\n' "$monitors_json"
        return 0
      fi
    fi
  fi

  return 1
}

json_array_from_lines() {
  if [ "$#" -eq 0 ]; then
    printf '[]'
    return
  fi

  printf '%s\n' "$@" | jq -Rsc 'split("\n") | map(select(length > 0))'
}

render_with_outputs() {
  local template="$1"
  local outputs_json="$2"
  local monitor_name="${3:-}"

  awk -v outputs_json="$outputs_json" -v monitor_name="$monitor_name" '
    /"name":/ && inserted == 0 {
      print
      printf "\"output\": %s,\n", outputs_json
      inserted = 1
      next
    }
    {
      line = $0
      if (monitor_name != "") {
        gsub(/__WAYBAR_MONITOR__/, monitor_name, line)
      }
      print line
    }
  ' "$template"
}

fallback_to_wide() {
  [ -f "$WIDE_TEMPLATE" ] || return 1
  cp -f "$WIDE_TEMPLATE" "$OUTPUT_FILE"
}

main() {
  local monitors_json
  local wide_outputs=()
  local narrow_outputs=()
  local uber_narrow_outputs=()

  mkdir -p "$CONFIG_DIR"

  if [ ! -f "$WIDE_TEMPLATE" ] || [ ! -f "$NARROW_TEMPLATE" ] || [ ! -f "$UBER_NARROW_TEMPLATE" ]; then
    fallback_to_wide
    return $?
  fi

  if ! command -v jq >/dev/null 2>&1; then
    fallback_to_wide
    return $?
  fi

  monitors_json="$(get_hypr_monitors_json)" || monitors_json=""
  if [ -z "$monitors_json" ] || [ "$monitors_json" = "[]" ]; then
    fallback_to_wide
    return $?
  fi

  while IFS=$'\t' read -r name width height scale transform; do
    [ -n "$name" ] || continue

    local effective_width="$width"
    if is_rotated_transform "$transform"; then
      effective_width="$height"
    fi

    effective_width="$(awk -v size="$effective_width" -v scale="$scale" 'BEGIN {
      if (scale == 0) scale = 1;
      printf "%.0f", size / scale
    }')"

    if [ "$effective_width" -lt "$UBER_NARROW_THRESHOLD" ]; then
      uber_narrow_outputs+=("$name")
    elif [ "$effective_width" -lt "$WIDTH_THRESHOLD" ]; then
      narrow_outputs+=("$name")
    else
      wide_outputs+=("$name")
    fi
  done < <(
    jq -r '.[] | [.name, (.width // 0), (.height // 0), (.scale // 1), (.transform // 0)] | @tsv' <<<"$monitors_json"
  )

  if [ "${#wide_outputs[@]}" -eq 0 ] && [ "${#narrow_outputs[@]}" -eq 0 ] && [ "${#uber_narrow_outputs[@]}" -eq 0 ]; then
    fallback_to_wide
    return $?
  fi

  {
    echo "/* Auto-generated by GenerateWaybarGreenscreen.sh */"
    echo "/* Tier thresholds: wide >= ${WIDTH_THRESHOLD}px, narrow >= ${UBER_NARROW_THRESHOLD}px, uber-narrow < ${UBER_NARROW_THRESHOLD}px */"
    echo
    echo "["

    local emitted=0
    if [ "${#wide_outputs[@]}" -gt 0 ]; then
      render_with_outputs "$WIDE_TEMPLATE" "$(json_array_from_lines "${wide_outputs[@]}")"
      emitted=1
    fi

    if [ "${#narrow_outputs[@]}" -gt 0 ]; then
      for i in "${!narrow_outputs[@]}"; do
        if [ "$emitted" -eq 1 ] || [ "$i" -gt 0 ]; then
          echo ","
        fi
        render_with_outputs "$NARROW_TEMPLATE" "$(json_array_from_lines "${narrow_outputs[$i]}")" "${narrow_outputs[$i]}"
        emitted=1
      done
    fi

    if [ "${#uber_narrow_outputs[@]}" -gt 0 ]; then
      for i in "${!uber_narrow_outputs[@]}"; do
        if [ "$emitted" -eq 1 ] || [ "$i" -gt 0 ]; then
          echo ","
        fi
        render_with_outputs "$UBER_NARROW_TEMPLATE" "$(json_array_from_lines "${uber_narrow_outputs[$i]}")" "${uber_narrow_outputs[$i]}"
        emitted=1
      done
    fi

    echo "]"
  } >"$OUTPUT_FILE"
}

main "$@"
